### ISSUE TITLE
Support for Log forwarding via Output profile

### ISSUE THREAD

**Issue by khamidziyo** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#11]
I couldn't find any module supports this feature: https://docs.fortinet.com/document/fortianalyzer/7.4.1/administration-guide/19991

**Comment by MaxxLiu22** [comment]
Hi @khamidziyo ,

Thank you for bringing up this question. I came across the [faz_cli_system_logforward](https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/docgen/faz_cli_system_logforward.html) module in the documentation and was able to successfully create an object using the following script. Please let me know if this aligns with what you were looking for.

```
  tasks:
  - faz_cli_system_logforward:
      bypass_validation: '{{bypass_validation}}'
      cli_system_logforward:
        fwd_max_delay: 5min
        fwd_server_type: fortianalyzer
        id: 1
        mode: forwarding
        server_addr: 12.3.4.5
        server_name: fooname
      state: '{{state}}'
    name: Test faz_cli_system_logforward
```
Thanks,
Maxx
