### ISSUE TITLE
Fortianalyzer ansible collection to get Log viewer

### ISSUE THREAD

**Issue by selvigp** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#12]
Hi,

I am automating fortianalyzer related tasks using Ansible.

I couldn't able to find out which module should we use for retrieving logs between two different devices in the Fortianalyzer. I have use fortianalyzer collection for the same, but issue with identify exact module for doing this specific tasks. 

Do we any ansible modules available for the same? Or should we look into alternative approach.

**Comment by MaxxLiu22** [comment]
Hi @selvigp ,

Thank you for your question. Are you trying to view the log of a FortiAnalyzer-managed device, such as through GUI → Log View → Logs? The [faz_fact](https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/faz_fact.html) module can accomplish the same function for you. Please let me know if this is not what you were looking for.
```
  tasks:
  - name: Fetch ADOM Traffic Log File
    fortinet.fortianalyzer.faz_fact:
      facts:
        selector: logview_logfiles_search
        params:
          adom: root
          limit: 50
          offset: 0
          logtype: ""
          devid: FGVMULTM24003288
          vdom: root
          filename: tlog.log
  - name: Fetch ADOM Event Log File
    fortinet.fortianalyzer.faz_fact:
      facts:
        selector: logview_logfiles_search
        params:
          adom: root
          limit: 50
          offset: 0
          logtype: ""
          devid: FGVMULTM24003288
          vdom: root
          filename: elog.log
```
Thanks,
Maxx

**Comment by selvigp** [comment]
Hi @MaxxLiu22 
Thanks for you response.
The idea here is to filter the logs between the two ip addr ( for e.g., b/n src ip & des ip) from fortianalyzer device. I am getting error such as 'faz_fact' module is not recognized by ansible automation platform while running playbook.  Is it mandate to specify filename here or not.

**Comment by MaxxLiu22** [comment]
Hi @selvigp ，

Thank you for your information. It seems that Ansible couldn't find the 'faz_fact' module. Are you referring to the latest Ansible FOS collection? For your reference, here is my full playbook.

It appears that FAZ stores different types of log information in separate files, such as "elog.log" for event logs and "tlog.log" for traffic logs. Therefore, you may need to specify the log file name in your playbook. Additionally, you can use logview_logfiles_state to check which log files are available.
```
root@liang:~/ansible/faz/github12# ansible-galaxy collection list | grep fortinet.fortianalyzer
fortinet.fortianalyzer                   1.8.0    <---------------------- latest virion
```
```
- collections:
  - fortinet.fortianalyzer      <--------------- refer the right collection
  connection: httpapi
  hosts: fortianalyzers
  tasks:
  - name: Check Log File status
    fortinet.fortianalyzer.faz_fact:
      facts:
        selector: logview_logfiles_state
        params:
          adom: root
  - name: Fetch ADOM Traffic Log File
    fortinet.fortianalyzer.faz_fact:
      facts:
        selector: logview_logfiles_search
        params:
          casesensitive: false
          adom: root
          limit: 50
          offset: 0
          filter:  "srcip=\"10.160.88.181\" dstip=\"173.243.143.6\""
          logtype: ""
          devid: FGVMULTM24003288
          vdom: root
          filename: tlog.log
    register: log_results

  - name: Save log file locally
    copy:
      content: "{{ log_results }}"
      dest: "tmp/tlog.json"


  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
```
Let me know if you still have questions.
Thanks,
Maxx
