### ISSUE TITLE
Support for exporting templates

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#13]
Hi!

Can you add support for exporting templates? Here is the API endpoint that is also documented in the FNDN: 
```
/report/template/export - Export report templates.
```

Thanks!

**Comment by dux-fortinet** [comment]
Hi @cr0cdev ,

"/report/template/export" is a "get" API.

All "get" APIs are supported in `"faz_fact"`.

Please try this:
```
- name: Export report template
  hosts: fortianalyzers
  connection: httpapi
  vars:
    adom_name: "root"
  tasks:
    - name: report_template_export
      fortinet.fortianalyzer.faz_fact:
        facts:
          selector: "report_template_export"
          params:
            adom: "{{adom_name}}"
            # Following params are optional
            # dev-type: "fgt"
            # language: "en"
            # title: "Template - 360 Protection Report" # Template title, filter for exporting report template.
      register: response
    - name: Base64 decode
      set_fact:
        decode_content: "{{ response.meta.response_data.data | b64decode }}"
    - name: Save content
      copy:
        content: "{{ decode_content }}"
        dest: "./test_import.tar.gz"
```

Regards,
Xinwei
