### ISSUE TITLE
Reboot FortiAnalyzer with api user

### ISSUE THREAD

**Issue by jacoob007-cyber** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#14]
Hello, I'm new user on ansible so please forgive me for any errors I make. I'm trying to reboot my FortiAnalyzer using the faz_sys_reboot module.

1. I have created an API user on FortiAnalyzer

2.  A host file as documentation suggest in the following format:

--host file--
[fortianalyzers]
fortianalyzer01 ansible_host=192.168.190.130 ansible_user="my_api_user" ansible_password="api_password"
 

[fortianalyzers:vars]
ansible_network_os=fortinet.fortianalyzer
ansible_httpapi_port=443
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
--host file--

3. A test.yaml file without including vars 
--yaml--
- name: Example playbook
  connection: httpapi
  hosts: fortianalyzers
  tasks:
    - name: Restart FortiAnalyzer.
      fortinet.fortianalyzer.faz_sys_reboot:
        sys_reboot:
          faz_message: Reboot Via Ansible
--yaml--

And when I try to run the playbook I'm getting the following error "fatal: [fortianalyzer01]: FAILED! => {
    "msg": "unable to load API plugin for platform type fortinet.fortianalyzer"
}"

Could you please help me, I'm trying to resolve the issue for along time without success.

**Comment by MaxxLiu22** [comment]
Hi @jacoob007-cyber ,

You are welcome to use our Ansible FAZ collection! It's understandable to encounter some challenges when using a new tool for the first time. It looks like there is a typo in your host file. The correct entry should be ``ansible_network_os=fortinet.fortianalyzer.fortianalyzer``. I understand that the repetition of "fortianalyzer" might be a bit confusing. Could you please check and add it to your host file? Let me know if that works!

Thanks,
Maxx

**Comment by jacoob007-cyber** [comment]
Hi @MaxxLiu22,

Thank you for your quick response!

I’m aware that the documentation specifies using ansible_network_os=fortinet.fortianalyzer.fortianalyzer. However, when I use this value, I encounter the following error:

"fatal: [fortianalyzer01]: FAILED! => {"changed": false, "msg": "No fact modules available and we could not find a fact module for your network OS (fortinet.fortianalyzer.fortianalyzer), try setting one via the FACTS_MODULES configuration."}"

If I change it to ansible_network_os=fortinet.fortianalyzer, I instead get:

"unable to load API plugin for platform type fortinet.fortianalyzer"

Could you advise on the correct configuration for this use case?

Thanks in advance for your help!

**Comment by MaxxLiu22** [comment]
Hi @jacoob007-cyber ,

Thank you for your response. You may need to temporarily disable ``gather_facts: false`` at the beginning of your playbook, as this issue might be caused by differences in Ansible versions. We will investigate this matter further. Apologies for any inconvenience caused.
```
- collections:
  - fortinet.fortianalyzer
  connection: httpapi
  hosts: fortianalyzers
  gather_facts: false  <--------------
  tasks:
......
```

**Comment by jacoob007-cyber** [comment]
Hello @MaxxLiu22 

I used the gather_facts on my playbook.
--playbook--
- name: Example playbook
  connection: httpapi
  hosts: fortianalyzers
  gather_facts: false
  tasks:
    - name: Restart FortiAnalyzer.
      fortinet.fortianalyzer.faz_sys_reboot:
        sys_reboot:
          faz_message: Reboot Via Ansible
        enable_log: true
--playbook--
 
It seems that now I'm receiving a different error "The error was: ansible.module_utils.connection.ConnectionError: Can't login. Your login method is username_password.Please check whether you provide the correct information."

As I mentioned above I have created an API user and the logon credentials are located on host file.

**Comment by MaxxLiu22** [comment]
If you are using an API user, you may need to define ``access_token`` in your playbook. Alternatively, ansible_user and ansible_password can be used for session-based authentication. If both methods are defined, Ansible FAZ will prioritize access_token as the primary authentication method and disregard the session-based login. You can generate token through following CLI.
```
config system admin user
    edit "api"
        set password ENC SH2UPLooKh0fcG7ItCA/4+XsNBZqRLRZ0y6XegPohWe9gDcVlwwRGZBcIfY5ik=
        set profileid "Super_User"  <----------- give permit as you need
        set user_type api
            config meta-data
                edit "Contact Email"
                next
                edit "Contact Phone"
                next
            end
        set rpc-permit read-write  <----------- give permit as you need
    next
end

(api)# end

asb_test # execute api-user generate-key api
New API key: jgs4ctf...wakpz8ex8xb9t  <----------- save this token, this will not show again

```
```
  tasks:
    - name: Restart FortiAnalyzer.
      fortinet.fortianalyzer.faz_sys_reboot:
        access_token:  jgs4ctf...wakpz8ex8xb9t   < ---------------- paste here
        sys_reboot:
          faz_message: Reboot Via Ansible
```

**Comment by dux-fortinet** [comment]
Thanks Maxx for the explanation. Here is a little more explanation: "access_token" is not an Ansible variable, the FortiAnalzyer Ansible Collection can't read this variable unless you specified it in the playbook.

Please try this:

[hosts file]
```
[fortianalyzers]
fortianalyzer760 ansible_host="<IP>" access_token="<Your access_token>"

[fortianalyzers:vars]
ansible_network_os=fortinet.fortianalyzer.fortianalyzer
ansible_httpapi_port=443
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
```

[example.yml file]
```
- name: Example playbook
  connection: httpapi
  hosts: fortianalyzers
  gather_facts: false # gather_facts: true works well in my environment, I will figure out why it causes "No fact modules available".
  tasks:
    - name: Restart FortiAnalyzer.
      fortinet.fortianalyzer.faz_sys_reboot:
        access_token: "{{ access_token }}" # <-you need to specify the access token here
        sys_reboot:
          faz_message: Reboot Via Ansible
```

Then run 
`ansible-playbook -i hosts 'example.yml'`

It works in my environment: ansible-core (2.18.1), FortiAnalyzer (7.6.0), FortiAnalyzer Ansible Collection (1.8.1)

For best practice, I would recommend not specifying both ansible_user/ansible_password and access_token at the same time.

Thanks.
