### ISSUE TITLE
Configuring SNMP via the provided api module does not work as expected

### ISSUE THREAD

**Issue by bhuddah** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#15]
When configuring snmp community the port is not open and does not respond.
the root cause is unknown by me. saving the created community via the gui corrects the behavior.
reproduction is possible via the example in fortinet.fortianalyzer.faz_cli_system_snmp_community

**Comment by MaxxLiu22** [comment]
Hi @bhuddah ,

Thank you for bringing up this issue. Could you please let me know which version of FAZ and Ansible FAZ collection you are using, as well as the specific SNMP community playbook you're referring to? On my side, the script is running successfully on FAZ version 7.6.1 and Ansible collection fortinet.fortianalyzer:1.9.0
```
  tasks:
    - name: SNMP community configuration.
      fortinet.fortianalyzer.faz_cli_system_snmp_community:
        cli_system_snmp_community:
          id: 3
          name: foosnmpcommunity3
          status: disable
          query_v1_port: 166
          query_v1_status: disable
        state: present
```
Thanks,
Maxx

**Comment by bhuddah** [comment]
We are using collection version 1.9.0
Fortianalyzer is on version v6.5.6, build1391 (GA)
And yes, the ansible task runs fine but snmp is not working.

**Comment by MaxxLiu22** [comment]
Hi @bhuddah ,

Thank you for the information. I noticed a possible typo in your message—I couldn’t find a v6.5.x release or any GA build with the number 1391. If you're currently using a v6.x version of FAZ, I would recommend upgrading to at least v7.2.x.

Older FAZ versions may no longer be eligible for engineering support, and there may also be differences in configuration behavior across versions.

You mentioned that the playbook successfully pushed the configuration to FAZ, but SNMP still isn’t working. It's possible that some additional arguments or settings need to be enabled for SNMP to function properly. If the SNMP configuration works correctly via the GUI, you might try opening the browser's Network Monitor (press F12) and re-performing the operation in the GUI. This can help you observe how the GUI handles the SNMP settings, which may provide clues on how to adjust your playbook—since both interfaces use the same API endpoints.

![Image](https://github.com/user-attachments/assets/55a1ec2f-b86d-4beb-8f20-d6ab72374032)

**Comment by bhuddah** [comment]
Sorry for the hassle, i read the version information from the wrong product.
We are dealing with v7.4.5 build2553 (Mature) here.

**Comment by MaxxLiu22** [comment]
Hi @bhuddah ,

I’m still unable to reproduce the issue on my end. Could you please confirm whether the port status is enabled?

Additionally, it would be very helpful if you could share your playbook and a screenshot of the GUI. This information will allow me to investigate the issue more thoroughly.
```
    - name: SNMP community configuration.
      fortinet.fortianalyzer.faz_cli_system_snmp_community:
        cli_system_snmp_community:
          id: 3
          name: foosnmpcommunity3
          status: enable
          query_v1_port: 167
          query_v1_status: disable
          query_v2c_port: 167
          query_v2c_status: enable
          trap_v1_rport: 167
          trap_v1_status: enable
          trap_v2c_rport: 167
          trap_v2c_status: enable
        state: present
```
Thanks,
Maxx
