### ISSUE TITLE
Wrong data type for faz_dvmdb_device_vdom

### ISSUE THREAD

**Issue by vincent-at-forti** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#2]
Using ansible faz_dvmdb_device_vdom.py module to create a FGT vdom in FAZ ADOM.
The query sent by ansible is the using a dictionary for the data :

```
 "params":[
      {
         "data":{ 
            "comments":"Commentaire",
            "name":"newVdomAnsible2",
            "opmode":"nat",				   
            "status":"present",
            "vpn_id":0
         },
         "target start":1,
         "url":"/dvmdb/adom/AdomAnsible/device/axion-api-kvm07/vdom"
      }
   ],
```

But the FAZ API is waiting for a list of dict:

```
   "params":[
      {
         "data":[
            {
               "comments":"New vdom",
               "name":"test221",
               "opmode":"nat",
               "rtm_prof_id":0,
               "status":"present",
               "vpn_id":0
            }
         ],
         "target start":1,
         "url":"/dvmdb/adom/AdomAnsible/device/axion-api-kvm07/vdom"
      }
   ],

```
So FAZ refuses with the following error:
{ "status": { "code": 1, "message": "runtime error 0: invalid value"}}

Maybe replacing the :

```
    dvmdb_device_vdom:
        description: the top level parameters set
        required: false
        type: dict
        suboptions:
```

by

```
  dvmdb_device_vdoms: 
          description: the top level parameters set
          required: false
          type: list
          suboptions:
```
