### ISSUE TITLE
faz_dvm_cmd_add_device not supporting 7.0 os version

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#3]
Hi!

Update:
Pull request has been created for the fix: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection/pull/4

I'm trying to add model device to FortiAnalyzer with OS version defined as 7.0, but as the documentation states and after trying it does not support version above 5.0. Is there a way around this and when would we expect it to support 7.0 as well.
Documentation states:
```
os_ver - add model device only. type: str choices: [unknown, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
```

This is my try to see if the documentation was just not updated:
```
- name: Add new model device to ADOM "{{ adom_name | lower }} on FortiAnalyzer"
  fortinet.fortianalyzer.faz_dvm_cmd_add_device:
    dvm_cmd_add_device:
      adom: "{{ adom_name | lower }}"
      device:
        name: "{{ device_name | lower }}"
        sn: "{{ serial_number | upper }}"
        os_ver: "{{ device_fos_ver }}"
        os_type: "{{ device_os_type }}"
        mr: "{{ device_fos_mr }}"
        mgmt_mode: "{{ device_faz_mgmt_mode }}"
        device action: "{{ device_action }}"
```
```
fatal: [fortianalyzer01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "bypass_validation": false,
            "dvm_cmd_add_device": {
                "adom": "ansible-test-2",
                "device": {
                    "adm_pass": null,
                    "adm_usr": null,
                    "desc": null,
                    "device action": "add_model",
                    "faz.quota": null,
                    "ip": null,
                    "meta fields": null,
                    "mgmt_mode": "faz",
                    "mr": 2,
                    "name": "fgt40f",
                    "os_type": "fos",
                    "os_ver": "7.0",
                    "patch": null,
                    "platform_str": null,
                    "sn": "FGT40XXXXXXXX"
                },
                "flags": null,
                "groups": null
            },
            "enable_log": false,
            "forticloud_access_token": null,
            "log_path": "/tmp/fortianalyzer.ansible.log",
            "rc_failed": null,
            "rc_succeeded": null
        }
    },
    "msg": "value of os_ver must be one of: unknown, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, got: 7.0 found in dvm_cmd_add_device -> device"
}
```
