### ISSUE TITLE
Support for reports (scheduling etc)

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#5]
Hi!
Is there any plan to add reporting API endpoints support as well? In the documentation there is no information that this collection supports scheduling reports etc.
FortiAnalyzer API documentation (https://fndn.fortinet.net/index.php?/fortiapi/175-fortianalyzer/3832/175/report/) states that these endpoints can be used to configure ADOM specific reports scheduling:
```
/report/run
/report/adom/<adom-name>/config/schedule
etc...
```

Thank you!

**Comment by dux-fortinet** [comment]
Hi cr0cdev,

The format of report APIs is quite different from other APIs. I will write new logic to support those report APIs manually.

I can support the following APIs in the next Fortianalyzer Ansible version
```
/report/run
/report/adom/<adom-name>/config/chart/*
/report/adom/<adom-name>/config/dataset/*
/report/adom/<adom-name>/config/layout/*
/report/adom/<adom-name>/config/layout-folder/*
/report/adom/<adom-name>/config/macro/*
/report/adom/<adom-name>/config/output/*
/report/adom/<adom-name>/config/schedule/*
```
(/report/adom/<adom-name>/config/schedule/* means all APIs starting with /report/adom/<adom-name>/config/schedule/, including /report/adom/<adom-name>/config/schedule/<schedule_name>/address-filter)

Please let me know if there are other APIs you want to use.

Currently, you can use the module "faz_generic" (https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/faz_generic.html) to call those APIs.

FortiAnalyzer Ansible is expected to be updated every 2 months. And since we just released a version 2 weeks ago, the next release will be in May. Please let me know if you need it urgently.

Best,
Xinwei

**Comment by cr0cdev** [comment]
Hi, Xinwei

Thanks for adding those. Could you also add these so it is possible to initiate reports downloading via Ansible.
```
/report/adom/<adom-name>/reports/state
/report/adom/<adom-name>/data/id
```  

It would be also good to add the templates to the automation as well in which case we could import/export/list them via automation.
```
/report/adom/<adom-name>/template/*
``` 

Regarding `/report/run` API path, could you also include `/report/adom/<adom-name>/run/<tid>` in which case we will be able to get the template run task information. I think we could use `faz_fact` for this as well, but I haven't tested it as I understand it takes the task from system task list. 

Thanks!

**Comment by dux-fortinet** [comment]
Hi @cr0cdev.

Sure, will do.

I just checked those report APIs in the FNDN. Those APIs are different than other APIs. (`faz_generic` doesn't support those APIs because those APIs have `"jsonrpc": "2.0"` in their request body, and `faz_generic` doesn't support it now. I will fix it in the next version.)

I will try to support those (get) method APIs in `faz_fact`. But since those APIs are in different formats, if I can't add those APIs to `faz_fact`, I will create a module to support those APIs.

The APIs we already supported, like` /cli/global/system/admin/profile`, have get, add, set, update, delete methods. So I can use one module to get/update/delete the corresponding resource. Yet those report APIs only have part methods. In this case, I will create different modules for different methods. (`/report/reports/data (delete)` and `/report/reports/data (get)` will be in different modules) and each module only supports one API-method pair.

In this case, the behavior of those report modules is more like a wrapper of the corresponding report API: each module reads YML format playbook, transfers it to JSON format, and sends it to API. 

Those APIs will be added in the next version. 

Thanks,
Xinwei

**Comment by cr0cdev** [comment]
Thanks Dux!

**Comment by cr0cdev** [comment]
@dux-fortinet do you have a ETA on when new FAZ collection that supports this will be released?

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

Sorry for the late update. We are working on other projects so this update may not be so timely.
New FAZ collection will be released 2 weeks later.
I'm expecting to release it before May 17th. (If everything goes well, we can release it before May 10th if possible)

Thanks,
Dux

**Comment by dux-fortinet** [comment]
This is the follow-up:
The development is finished, and FortiAnalyzer Ansible is in the QA process. The new version is expected to be released this Friday or early next week. Thanks for your patience.

**Comment by dux-fortinet** [comment]
FortiAnalzyer Ansible 1.5.0 has been release. All report APIs are supported in this version.

For the APIs that only get information, and don't change data in FortiAnalyzer, they are supported by `faz_fact`, for other APIs, you can find the relationship between APIs and modules on [this page](https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/digest.html).

Following are some `faz_fact` examples.

Download generated report. `/report/reports/data/<tid> (get)`
```
- name: Download generated report
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    adom_name: "root"
    task_id: "6d99e7b0-0bf0-11ef-85b2-000c293bfd45"
  tasks:
    - name: report_reports_data
      fortinet.fortianalyzer.faz_fact:
        facts:
          selector: "report_reports_data"
          params:
            adom: "{{adom_name}}"
            tid: "{{task_id}}"
            # data-type: "text"
            format: "PDF" # HTML, PDF, XML, CSV
      register: response
    # - name: Display data
    #   debug:
    #     var: response.meta.response_data.data

    # Zipped and Base64 encoded data by default. 
    # Plain text for XML and CSV when specified (data-type: "text") in request.
    - name: Base64 decode
      set_fact:
        decode_content: "{{ response.meta.response_data.data | b64decode }}"
    - name: Save content
      copy:
        content: "{{ decode_content }}"
        dest: "./{{task_id}}.zip"
```

List reports. `/report/reports/state (get)`
```
- name: List reports
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    adom_name: "root"
  tasks:
    - name: report_reports_state
      fortinet.fortianalyzer.faz_fact:
        facts:
          selector: "report_reports_state"
          params:
            adom: "{{adom_name}}"
            state: "generated" # or "pending-running"
            time-range: # It is required only if "state" is "generated".
              start: "2024-04-17T20:00:00-07:00"
              end: "2024-05-17T20:00:00-07:00"
            # Following params are optional
            # sort-by:
            #   - filed: ""
            #   - order: "asc"
            # timezone: "string"
            # title: "string"
      register: response
    - name: Display response
      debug:
        var: response
```

Export report templates. `/report/template/export (get)`
```
- name: Export report template
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    adom_name: "root"
  tasks:
    - name: report_template_export
      fortinet.fortianalyzer.faz_fact:
        facts:
          selector: "report_template_export"
          params:
            adom: "{{adom_name}}"
            # Following params are optional
            # dev-type: "fgt"
            # language: "en"
            # title: "my_template" # Template title, filter for exporting report template.
      register: response
    - name: Base64 decode
      set_fact:
        decode_content: "{{ response.meta.response_data.data | b64decode }}"
    - name: Save content
      copy:
        content: "{{ decode_content }}"
        dest: "./template.tar.gz"
```

List report templates for a specified language. `/report/template/list (get)`
```
- name: Get template list
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    adom_name: "root"
  tasks:
    - name: report_template_list
      fortinet.fortianalyzer.faz_fact:
        facts:
          selector: "report_template_list"
          params:
            adom: "{{adom_name}}"
            # Following params are optional
            # dev-type: "fgt"
            # language: "en"
      register: response
    - name: Display response
      debug:
        var: response
```

**Comment by cr0cdev** [comment]
Thanks @dux-fortinet you're a life saver with this :)

**Comment by dux-fortinet** [comment]
You're welcome.  If you have any questions about report modules, please feel free to let me know.

**Comment by cr0cdev** [comment]
> You're welcome. If you have any questions about report modules, please feel free to let me know.

I have a question regarding importing report templates. I tried to import a template, but it seems like the API endpoint is missing ADOM parameter.
```
- name: Import weekly report
  fortinet.fortianalyzer.faz_report_template_import:
    report_template_import:
      data: "{{ lookup('file', './templates/reports/template.tar.gz') | b64encode }}"
      dev_type: "fgt"
    enable_log: true
```

```
fatal: [demolabfaz01]: FAILED! => {
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "bypass_validation": false,
            "enable_log": true,
            "forticloud_access_token": null,
            "log_path": "/tmp/fortianalyzer.ansible.log",
            "rc_failed": null,
            "rc_succeeded": null,
            "report_template_import": {
                "data": "H4sIAAwwT2YAA+1abXPaOBDmc37Fju/uWwyyAZtQwkyaXprc9CadJk3uOswwwpaNWltSJUFwOv3vNzKGAOGlvZB02vB8IWiX3dW+aS3nLR6dEhwSWdEkFQnWpLR1IIT8eh1KCDl+Hc1+juH6dXBqnlv1XN/3HUBO3XHqJRht35T7GCiNZQmh+PONc9BAK/k20cdbgennT4IqglTTlBw6vuPVvLpX98ue36g2XOS6e40GvDl7efTu+PTs6s/yCGsty4oEA0l1VlYkoWwwOgyv6x97bj3F1/Xkw8mBc54eUJxefQxPDrJzdnX74Z+/Ivz6QH+4OkDn7O+bo6M934GL49OzN/+ukjlgAWcRZSTsDpq895EEuiubA0Vkt89T0tVNhUp7P9p5vwAmVV95RB2b6t/Uy3z9V13HLUH9EW2a4pnX/zT+b+8dBKrcw4p4tQfrQAh5tdqa/l/1J/Gv+24NkIscb9f/nwS7Dv+8Ma3/rVf9HTbV/0z/H9e/47kIlWB1sW0Rz7z+1/Z/U6Fb0LGx/y/O/y5C1dqu/z8FdvP/88aS/r+lqr/Dhvr3ao63MP97yPN2/f8pkJdZDOpzYksiuNSQ4IwP9B4AAAmpBiePEUI1N18zUERDL7YDnnAJ1m8nOax5Mg8zsFohHYLSWUIOO9YNDXW/6SD0R8dqt/pOu6UEZlNylHCsmwmJ9AuIONO2orek6SIx6ljta0I+JRlcDNIUywze5aa2OhUjod3qVO5Jy21rxpJks9IcJEYvQOAwpCy2ja58qWO1X2GN4fcvphUKIikPv85ID+mw3dK4l5AVm9Fmu+2Wlu2WDqc8QyI1DXBi44TGrKm5MLwRvg36WGpIP5HMSMq3Zhdbsy8ljiIa2C8xC3Ml9hvKSMcCTXUutWNBvn7YsRr1sfGtTmUi1fytww1mvBhLaLrI+MMIEIvBuAuAN1YR4dsUB5KvMptrnNwZPTUq/017xpdinTKnkSsrfADvFY7J/G/Hu+tUjKs7lcLvnUoenO+I0eYwcGEfCTHj90su4EiIhAZYU86gl8EFGRJzbM2ExEdrQvKtWgOsZ1250oRjrEnM5az+6uqUeLDTHpjYXNiXfUmwVgtbGq9+qxMfbsUrnmLKFoy4Jj1FNTFhLdLvp/DqGQtoSJhWdi+zZ/JxsrUpfUW+ug9w9f3mDu6koRRNc3tBO+apkDylioT2KVdzSTRDA0Ob2V/tcVPpvSJyIZHM0vIsWmPLiiyaP1ODotzBuijm5QW6kWhTFnE7pEokOIOQKiNono0PiRQ4JnYPB59iyQcstGmKYwLWF5WpLk3jrsC6/7VTCUnUzfm7vdgshyQaumXBYmuFSMKMPjswFU1sc5zCeGk9v2G0xwfvev6Ic02k3YuL4UNLzJTAkjC9yiRNRno6q4zHs5WsJo5gfQlJhAeJ/jrPFxIVSCry1mu9lUQRpgFDT1ISgSpGk2KKwj0+0KDHObAPOm9x+4CF2AfzGLMPtKjMfQhm0rfPlQbMQlAcOCsvGjC0dSYInHCp6Wus572Un6PrNpozRDilSQbWuSAMLjBTS3jMYQyOu0CY9/zSsa+fXyFsYqIhKabNwuNoCZ3f0HCBQFmQDEJik1TozM7TXS1LF6rsyePMMnKCWTzI052wecvMRGinWMaUgTdH4ZKaRWduUUiuSaDJ0pydbBDHYJkI42AhQyWN+yu0qWFgJzRY2H6RnZeTrdmwdCy+02JQDPjjwMxRYDrh31ueajTJFkss+jRYyVTQwYpMVjKiu2bsnm8SEzAy0nOLhIXLzB0n2/8yN6WM5hX97cpzgvnyo5/Gnh5r7/9oGqst6PiO9/9e1fHz+7/a7v7vSbBw/1dr1Pxy3fE910c1b3f/98tjyf2fqfqt/jvAd7z/H9e/4zk1Z/f+f4cddtjhMfEfjfRZ/QAqAAA=",
                "dev-type": "fgt",
                "dev_type": "fgt"
            },
            "version_check": false
        }
    },
    "meta": {
        "request_url": "/report/template/import",
        "response_data": [],
        "response_error": {
            "code": -32603,
            "message": "Internal error: Report template import failure"
        },
        "response_message": "",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "2487",
            "Build": "2487",
            "Current Time": "Thu May 23 15:11:04 EEST 2024",
            "Daylight Time Saving": "Yes",
            "Disk Usage": "Free 454.08GB, Total 491.08GB",
            "FIPS Mode": "Disabled",
            "Hostname": "FAZ",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 10000,
            "Minor": 4,
            "Patch": 3,
            "Platform Full Name": "FortiAnalyzer-VM64",
            "Platform Type": "FAZVM64",
            "Release Version Information": " (GA)",
            "Serial Number": "FAZ-",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.4.3-build2487 240514 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": -32603
}
```

I also tried to import a template that I downloaded directly from FAZ (_.dat_) and it still failed to import it.

Thanks!

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

The report template APIs accept "tar/base64" format data, so (.dat) may not work. I decoded and unzipped your data ("data": "H4sIAAwwT2YAA+1abXPaOBD...). I found your have one extra folder 'template', and FAZ may not parse it correctly.
```
./template/templates.imgs
./template/templates.base64 # this one maybe is not part of FAZ configuration file
./template/templates.conf
```
Please use `tar czvf templates.tar.gz *` under the folder `template`, so `templates.tar.gz` contains at least following:
```
./templates.imgs
./templates.conf
```

Further more, API endpoints `/report/template/import (add)` and `/report/template/delete (add)` may not be used to add and delete template. I tried those APIs and checked templates in GUI, and those APIs can't add/delete template. I'm consulting with FAZ dev team to figure out the usage of those two APIs.

 **I'm able to add a template in FAZ 7.4.2 by using `faz_report_template_install`**
```
- name: Install report template
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Install weekly report
      fortinet.fortianalyzer.faz_report_template_install:
        adom: "root"
        report_template_install:
          data: "{{ lookup('file', '../templates_fixed.tar.gz') | b64encode }}"
          language: 'en'
```

One more thing, for FAZ 7.4.2, I could install your template successfully by both GUI (Reports->Report Denfinitions->Templates->More->Install Template Pack) and Ansible methods (mentioned above). For FAZ 7.4.3 I can't install your template via either method (I can install my test templates generated by FAZ 7.4.2). Maybe some data in your template is not compatible with FAZ 7.4.3


And for `fortinet.fortianalyzer.faz_report_config_schedule`, it seems there are differences between the schema in [FNDN](https://fndn.fortinet.net/index.php?/fortiapi/175-fortianalyzer/3621/175/report/) and the real schema that FAZ accept. Please use `bypass_validation: true` in the playbook so Ansible won't check the type of `schedule-valid-start` and `schedule-valid-end`. Sorry for this mismatch, we will fix it in the next release.
`schedule-valid-start` and `schedule-valid-end` accept `["00:00", "2023/05/25"]` or `"2024/05/25 16:09:53"`

I'm running out of time today, I haven't figured out how to configure all parameters in `fortinet.fortianalyzer.faz_report_config_schedule`. Following is just an illustration of how to set `schedule-valid-start` and `schedule-valid-end`.

```
- name: Schedule
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Report schedule
      fortinet.fortianalyzer.faz_report_config_schedule:
        bypass_validation: true
        adom: root
        state: present
        report_config_schedule:
          name: "9"
          description: "test"
          devices:
            - devices-name: "All_Device"
          schedule-valid-start: ["00:00", "2023/05/25"] # accept format 1
          # schedule-valid-start: "2024/05/25 16:09:53" # accept format 2
          schedule-valid-end: null # never end

          # other parameters...
          # report-layout: 
          # - is-global: 0
          #   layout-id: 9
```

PS: It seems you need to config faz_report_config_report and set `report-layout` in faz_report_config_schedule correctly, otherwise, the GUI 'Reports->Advanced Settings->Report Calendar' may not display correctly.

**Comment by cr0cdev** [comment]
Thanks @dux-fortinet for excellent explanation. I owe you a  :beer: :smile:

**Comment by cr0cdev** [comment]
Thanks @dux-fortinet 
I've tried to modify predefined reports schedule using the module and sadly it does not allow me to do it. 
Without defining language:
```
failed: [fortianalyzer01] (item={'name': 'Daily Summary Report', 'disp_name': 'Daily Summary Report', 'desc': 'Testing', 'state': 'present', 'status': 'enable', 'layout_id': 1000060042, 'output_format': 'pdf', 'schedule_type': 'every-n-days', 'time_period': 'yesterday', 'week_start': 'mon'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "ansible-test-1",
            "bypass_validation": true,
            "enable_log": false,
            "forticloud_access_token": null,
            "log_path": "/tmp/fortianalyzer.ansible.log",
            "proposed_method": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "report_config_schedule": {
                "description": "Testing",
                "name": "Daily Summary Report",
                "output_format": "pdf",
                "report_layout": [
                    {
                        "layout_id": "1000060042"
                    }
                ],
                "schedule_type": "every-n-days",
                "status": "enable",
                "time_period": "yesterday",
                "week_start": "mon"
            },
            "state": "present",
            "version_check": false
        }
    },
    "item": {
        "desc": "Testing",
        "disp_name": "Daily Summary Report",
        "layout_id": 1000060042,
        "name": "Daily Summary Report",
        "output_format": "pdf",
        "schedule_type": "every-n-days",
        "state": "present",
        "status": "enable",
        "time_period": "yesterday",
        "week_start": "mon"
    },
    "meta": {
        "request_url": "/report/adom/ansible-test-1/config/schedule",
        "response_data": {
            "status": {
                "code": -10131,
                "message": "datasrc invalid. object: sql-report schedule.1000060042:language. detail: en. solution: data not exist"
            }
        },
        "response_message": "",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Mon May 27 09:38:11 EEST 2024",
            "Daylight Time Saving": "Yes",
            "Disk Usage": "Free 135.32GB, Total 146.64GB",
            "FIPS Mode": "Disabled",
            "Hostname": "FAZ",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Minor": 2,
            "Patch": 4,
            "Platform Full Name": "FortiAnalyzer-VM64-HV",
            "Platform Type": "FAZVM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FAZ-",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": -10131
}
```
With defining language:
```
`failed: [fortianalyzer01] (item={'name': 'Daily Summary Report', 'disp_name': 'Daily Summary Report', 'desc': 'Testing', 'state': 'present', 'status': 'enable', 'layout_id': 1000060042, 'output_format': 'pdf', 'schedule_type': 'every-n-days', 'time_period': 'yesterday', 'week_start': 'mon', 'language': 'en'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "access_token": null,
            "adom": "ansible-test-1",
            "bypass_validation": true,
            "enable_log": false,
            "forticloud_access_token": null,
            "log_path": "/tmp/fortianalyzer.ansible.log",
            "proposed_method": null,
            "rc_failed": null,
            "rc_succeeded": null,
            "report_config_schedule": {
                "description": "Testing",
                "name": "Daily Summary Report",
                "output_format": "pdf",
                "report_layout": [
                    {
                        "layout_id": "1000060042"
                    }
                ],
                "schedule_type": "every-n-days",
                "status": "enable",
                "time_period": "yesterday",
                "week_start": "mon"
            },
            "state": "present",
            "version_check": false
        }
    },
    "item": {
        "desc": "Testing",
        "disp_name": "Daily Summary Report",
        "language": "en",
        "layout_id": 1000060042,
        "name": "Daily Summary Report",
        "output_format": "pdf",
        "schedule_type": "every-n-days",
        "state": "present",
        "status": "enable",
        "time_period": "yesterday",
        "week_start": "mon"
    },
    "meta": {
        "request_url": "/report/adom/ansible-test-1/config/schedule",
        "response_data": {
            "status": {
                "code": -10131,
                "message": "datasrc invalid. object: sql-report schedule.1000060042:language. detail: en. solution: data not exist"
            }
        },
        "response_message": "",
        "system_information": {
            "Admin Domain Configuration": "Enabled",
            "BIOS version": "04000002",
            "Branch Point": "1460",
            "Build": "1460",
            "Current Time": "Mon May 27 09:38:50 EEST 2024",
            "Daylight Time Saving": "Yes",
            "Disk Usage": "Free 135.32GB, Total 146.64GB",
            "FIPS Mode": "Disabled",
            "Hostname": "FAZ",
            "License Status": "Valid",
            "Major": 7,
            "Max Number of Admin Domains": 2,
            "Minor": 2,
            "Patch": 4,
            "Platform Full Name": "FortiAnalyzer-VM64-HV",
            "Platform Type": "FAZVM64-HV",
            "Release Version Information": " (GA)",
            "Serial Number": "FAZ-",
            "TZ": "Europe/Helsinki",
            "Time Zone": "(GMT+2:00) Helsinki, Riga,Tallinn.",
            "Version": "v7.2.4-build1460 230926 (GA)",
            "x86-64 Applications": "Yes"
        }
    },
    "rc": -10131
}
```
Not exactly sure if I need to create a brand new layout with the same settings as predefined report and then schedule the new report (_which wouldn't be a ideal solution_).

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

I thought you wanted to create a brand new schedule (which is a little bit hard and complex and I'm still investing in it). If you just want to modify the existing schedule, it is much easier. 

You don't need to specify `report_layout` under `report_config_schedule` if you just want to update the existing schedule. You just need to specify the parameter you want to update, and the rest of the parameters will be unchanged.

Everything in your previous playbook is correct except the "name". The name for "report_config_schedule" is a digital ID rather than a string. The ID of "Daily Summary Report" is "10042"

Following playbook works well in my test environment:
```
    - name: Report schedule
      fortinet.fortianalyzer.faz_report_config_schedule:
        bypass_validation: true
        adom: "{{adom_name}}"
        state: present
        report_config_schedule:
          name: "10042"
          description: "Daily Summary Report" # Changing the description does not affect the data in the GUI
          output_format: "pdf" # Maybe no need for FAZ 7.x
          schedule_type: "every-n-days"
          status: "enable"
          time_period: "yesterday"
          week_start: "mon"
          schedule-valid-start: ["11:55", "2023/05/23"]
          schedule-valid-end: null # never end
          # more parameters....
```

Thanks,
Dux
