### ISSUE TITLE
IoC Rescan module

### ISSUE THREAD

**Issue by mbdraks** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#6]
![Screenshot 2024-05-08 at 12 18 09 PM](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection/assets/2147047/f098cf3c-2c17-4e16-9d61-780fbd26e230)

Hi! Can you please confirm if there's a way to configure the parameters at the IoC Rescan settings with the existing modules?

I already investigated the existing [faz_cli_system_log_ioc](https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/docgen/faz_cli_system_log_ioc.html) module but that is not the same (I confirmed that cli settings under `conf sys log ioc` will be changed using that module) however that setting does not modify the parameters on the IoC Rescan page in the screenshot.

Checking the API call it seems to be around config/adom/root/ueba/ioc-rescan and cli/global/system/log/ioc but I was not able to find the proper modules. Can you please point me in the right direction? The goal is to enable the flag "Enable Current ADOM Indicator of Compromise Rescan", update the "Running at" to "package update" and customize the "Last N Days" from 14 to 30.

**Comment by dux-fortinet** [comment]
Hi @mbdraks,

Thanks for raising this issue. FortiAnalyzer Ansible Collection doesn't have modules related to IoC Rescan settings. Currently 
FortiAnalyzer Ansible Collection only supports the APIs in the [FNDN](https://fndn.fortinet.net/index.php?/fortiapi/175-fortianalyzer/)

FortiAnalyzer Ansible Collection communicates with FortiAnalyzer by sending requests to `https://<your-ip>/jsonrpc`. Based on my tests, in the GUI, the IoC Rescan-related update requests will be sent to the APIs (`https://<your-ip>/p/fortiview/ioc/global/config/set/` and `https://<your-ip>/p/fortiview/ioc/rescan/config/set/`), this is quite different from how FortiAnalyzer Ansible works.

I checked the APIs in FNDN and tried some APIs, and I can't find any JSON API related to IoC Rescan settings yet.

I will consult my colleagues and give you a solution as soon as we find one.

Thanks,
Dux

**Comment by dux-fortinet** [comment]
Hi @mbdraks,

Here is the solution:
To `update the "Running at" to "package update"`, you can use the module `faz_cli_system_log_ioc`, however, `change "Last N Days" from 14 to 30` and `Enable Current ADOM Indicator of Compromise Rescan` using API `config/adom/root/ueba/ioc-rescan` which is not supported by FortiAnalyzer Ansible Collection right now since this API is not in the FNDN. Yet you can always use [faz_generic](https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest/faz_generic.html) to send customized JSON requests by yourself.

Here is the example playbook that fits your needs.
```
- name: Config IoC
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Indicator of Compromise Rescan Global Settings
      fortinet.fortianalyzer.faz_cli_system_log_ioc:
        cli_system_log_ioc:
          rescan_run_at: 0 # 0 means "package update"
          rescan_status: "enable"
          status: "enable"
    - name: Indicator of Compromise Rescan Current ADOM Settings
      fortinet.fortianalyzer.faz_generic:
        method: "set"
        params:
          - url: "config/adom/root/ueba/ioc-rescan"
            data:
              last-ndays: 30
              status: "enable"
```

Thanks,
Dux
