### ISSUE TITLE
Customizing widgets at FortiView Custom View Dashboard

### ISSUE THREAD

**Issue by mbdraks** [fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection#7]
Hello,

I'm trying to build a dashboard similar to this using the API (just an example):

![Screenshot 2024-05-17 at 2 33 29 PM](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection/assets/2147047/336788d9-ca8c-4c48-94cd-75eb632551fb)

I was able to find how to create a new custom dashboard view (a new tab inside Custom Views), with this playbook:

``` yaml
- name: Create a new custom view dashboard for user noc
  fortinet.fortianalyzer.faz_generic:
    rc_succeeded: [-2] # Object already exists
    method: "add"
    params:
      - url: "config/adom/root/{{ user }}/dashboard"
        data:
          - name: "{{ dashboard_name }}"
            user: "{{ user }}"
            uuid: "{{ formatted_uuid }}"
```

Now the challenge is to populate the widgets within the dashboard. The data structure for this endpoint (`config/adom/root/{{ user }}/dashboard`) looks like this:

``` json
{
    "data": [
        {
            "created-from": "",
            "dash-data": "null",
            "is-fv": false,
            "is-private": false,
            "name": "test",
            "theme": "",
            "user": "noc",
            "uuid": "de6b5aca-ba0b-45cf-b53b-b82c7a08ca1c",
            "widgets": "[]"
        }
    ]
}
```

However I was unable to properly populate the widgets parameter with the right list.

Another thing that I tried was inspecting browser requests, I came to the endpoint `noc/save_dash` but I was also unable to properly send the widget data to build the view.

Here's what I tried:

``` yaml
- name: customize widgets on an existing custom view
  fortinet.fortianalyzer.faz_generic:
    # rc_succeeded: [-2] # Object already exists
    method: "add"
    params:
      - url: "noc/save_dash"
        data:
          - uuid: "{{ formatted_uuid }}"
            dash:
              uuid: "{{ formatted_uuid }}"
              dash-data: {}
              widgets:
                - name: "top_source"
                  grid:
                    id: "top_source"
                    cells: 2
                - name: "fortiview_top_destination"
                  grid:
                    id: "fortiview_top_destination"
                    cells: 2
                - name: "top_threat"
                  grid:
                    id: "top_threat"
                    cells: 2
```

Any suggestions on how I can achieve this goal?

**Comment by dux-fortinet** [comment]
Hi @mbdraks,

I used FortiAnalyze 7.4.2. Here is what I found:

If I already created a dashboard in 'custom views', I can update the existing one by using:
```
- name: Update a custom view dashboard
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Update a custom view dashboard
      fortinet.fortianalyzer.faz_generic:
        # method: "add": create a new one.
        # method: "update": update an existing one.
        # method: "set": create a new one if not exist, else, update the existing one.
        method: "set"
        params:
          - url: "config/adom/root/noc/dashboard" # it should be "config/adom/root/noc/dashboard" rather than "config/adom/root/{{ user }}/dashboard"
            data:
              - name: "gui2"
                user: "admin"
                uuid: <existing custom view uuid>
                # widgets data should be a string. Otherwise, the fortianalyzer may not be able to parse it correctly.
                widgets: '[{"name": "virus_timeline", "grid": {"id": "virus_timeline", "cells": 4}, "props": {}}]'
```

However, if I use the above script to create a new dashboard, this dashboard will not display in the 'custom views'.

I guess a dashboard is not necessary to be displayed on the 'custom views' page.

If I use the following script to get all dashboard data, I will get some other dashboards such as "Data Leak Prevention", "Indicator of Compromise", "Local System Performance", etc. (You can find those dashboards on other pages)
```
- name: Get fact
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Get dashboard data
      fortinet.fortianalyzer.faz_generic:
        method: "get"
        params:
          - url: "/config/adom/root/noc/dashboard"
      register: response
    - name: Display response
      debug:
        var: response.meta.response_data
```

To create a dashboard in 'custom views', the browser sent data to `https://<your_fortianalyzer_ip>/p/noc/create_dash/`, and this is not a standard JSON RPC request which FAZ Ansible used, since all JSON RPC requests will be sent to `https://<your_fortianalyzer_ip>/jsonrpc`

I will investigate it and give you more suggestions next week.

Have a great weekend,
Dux

**Comment by mbdraks** [comment]
> `# it should be "config/adom/root/noc/dashboard" rather than "config/adom/root/{{ user }}/dashboard"`

Ah, it makes sense that it worked for me, because coincidentally the user that I was testing this was named `noc`.

Looking forward for your help after your investigation, thank you!

**Comment by dux-fortinet** [comment]
Here is the update:

I'm not able to find the corresponding JSON RPC API to create a dashboard in 'Custom Views'. I have already created an internal ticket and asked the FortiAnalzyer Dev team about it. I will let you know once they have a solution.

But if you are able to create a new custom dashboard view and just want to populate the widgets within the dashboard, the following script works in my test environment:

```
- name: Create/update a custom view dashboard for user
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Create/update a custom view dashboard for user
      fortinet.fortianalyzer.faz_generic:
        method: "set"
        params:
          - url: "config/adom/root/noc/dashboard"
            data:
              - name: <existing custom view name>
                user: <your username>
                uuid: <existing custom view uuid>
                # widgets data should be a string. Otherwise, the fortianalyzer may not be able to parse it correctly.
                widgets: '[{"name": "top_source", "grid": {"id": "top_source", "cells": 2}}, {"name": "fortiview_top_destination", "grid": {"id": "fortiview_top_destination", "cells": 2}}, {"name": "top_threat", "grid": {"id": "top_threat", "cells": 2}}]'
```

Please note widgets data should be a string.

One easy way to get string format widgets data is to manually create a custom view via GUI first, and then get its string format widgets data by using

```
- name: Get fact
  hosts: fortianalyzers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Get dashboard data
      fortinet.fortianalyzer.faz_generic:
        method: "get"
        params:
          # if you don;t know the uuid, url can be "/config/adom/root/noc/dashboard/", it will return all dashboard data
          - url: "/config/adom/root/noc/dashboard/<existing custom view uuid>" 
      register: response
    - name: Display response
      debug:
        var: response.meta.response_data
```

**Comment by mbdraks** [comment]
Dux, thank you! 

I will use this method until a better option becomes available.

**Comment by mbdraks** [comment]
Dux, just wanted to contribute back the final playbooks I used here in case it's useful for someone else.

For the get dashboard playbook I'm now directing the widgets output to a json file, so it's easier to inspect and modify:

```yaml
#!/usr/bin/env ansible-playbook
---
- hosts: all

  vars:
    uuid: cb78978a-063e-4e9e-be8d-74610588f878

  tasks:
    - name: Get dashboard data
      fortinet.fortianalyzer.faz_generic:
        access_token: "{{ access_token }}"
        method: get
        params:
          - url: /config/adom/root/noc/dashboard/{{ uuid }}
      register: response

    - name: Display response
      ansible.builtin.debug:
        var: response.meta.response_data

    - name: Save widgets to JSON file
      ansible.builtin.copy:
        content: "{{ response.meta.response_data.widgets }}"
        dest: files/widgets.json
```

and for the set dashboard playbook, I'm loading the data from the json definition:

```yaml
#!/usr/bin/env ansible-playbook
---
- hosts: all

  vars:
    uuid: cb78978a-063e-4e9e-be8d-74610588f878
    user: noc
    custom_view_name: Threats and IoC
    widgets_file: ../files/widgets.json

  tasks:
    - name: Read widgets from file
      set_fact:
        widgets: "{{ lookup('file', '{{ widgets_file }}') }}"

    - name: Create/update a custom view dashboard for user
      fortinet.fortianalyzer.faz_generic:
        access_token: "{{ access_token }}"
        method: set
        params:
          - url: config/adom/root/noc/dashboard
            data:
              - name: "{{ custom_view_name }}"
                user: "{{ user }}"
                uuid: "{{ uuid }}"
                widgets: "{{ widgets | to_json }}"
```

Thanks again, this is working fine.
